export const data = [
  { id: "libft", image: "libft" },
  { id: "printf", image: "ft_printf" },
  { id: "get", image: "get_next_line" },
  { id: "cub3d", image: "cub3d" },
  { id: "minishell", image: "minishell" },
  { id: "philo", image: "philosophers" },
  { id: "push", image: "push_swap" },
  { id: "long", image: "so_long" },
  { id: "fdf", image: "fdf" },
  { id: "fract", image: "fract-ol" },
  { id: "born2beroot", image: "born2beroot" },
  { id: "transcendence", image: "ft_transcendence" },
  { id: "minirt", image: "minirt" },
  { id: "pipex", image: "pipex" },
  { id: "webserv", image: "webserv" },
  { id: "netpractice", image: "netpractice" },
  { id: "minitalk", image: "minitalk" },
  { id: "irc", image: "ft_irc" },
  { id: "inception", image: "inception" },
];
